### ISSUE TITLE
Support for float[] sample 

### ISSUE THREAD

**Issue by patachi** [lostromb/concentus.oggfile#2]
trying to convert mp3 to opus ogg 
NAudio give float[] sample provider 

[stackoverflow question](http://stackoverflow.com/questions/42438014/naudio-float-sample-and-concentus-oggfile-short-sample-convert-mp3-to-opus-ogg)
this code doesn't work, can u help me with this ?

    using (var source = new MemoryStream(mp3File))
    using (var mp3Reader = new MyAudioFileReader(source, FileReaderType.Mp3))
    using (var memo = new MemoryStream())
    {
    	var bufferFloat = new float[mp3Reader.Length / (mp3Reader.WaveFormat.BitsPerSample / 8)];
    	var count = mp3Reader.Read(bufferFloat, 0, bufferFloat.Length);
    
    	//convert float to short 
    	var buffShort = new short[count];
    	var scale = (float)(short.MaxValue);
    	for (int i = 0; i < count; i++)
    	{
    		buffShort[i] = (short)(bufferFloat[i] * scale);
    	}
    	//encoder
    	var encoder = OpusEncoder.Create(48000, 
    		mp3Reader.WaveFormat.Channels, 
    		OpusApplication.OPUS_APPLICATION_AUDIO);
    		
    	encoder.Bitrate = 65536;//64kbps
		
    	//tags
    	var tags = new OpusTags();
    	tags.Fields[OpusTagName.Title] = "Title";
    	tags.Fields[OpusTagName.Artist] = "Artist";
		
		//
    	var oggOut = new OpusOggWriteStream(encoder, memo, tags);
    	
    	oggOut.WriteSamples(buffShort, 0, buffShort.Length);
    	oggOut.Finish();
    	   
    	result = memo.ToArray();
    }

**Comment by lostromb** [comment]
Hmmmm....hard to tell what the actual problem is. Are you passing the right length into mp3Reader.Read(bufferFloat.Length)? (I.e. does it expect length to be number of samples or number of bytes?)
I assume _scale_ is 32768?
Honestly, I.....can't really see anything wrong in the ogg stream code. The only potential problem would be that the MP3 would decode to 44100Khz and the encoder expects 48000 so it'll get pitch-shifted, but you should still get some output.
It might also help to use file streams for input and output rather than just putting the entire mp3 into a single buffer and encoding it into another buffer, if buffer flushing is causing some kind of issue.
I am publishing a new version of the OggFile library that has a native float[] encode function as well as automatic resampling. Let me know if that solves your problem

**Comment by patachi** [comment]
welp... the problem was my Android App (Telegram) that its player doesn't support opus with 2 channel  :/
(i was codding on remote server and limited time on whole new subject for me and etc ...) anyway when i back home and test it on my PC well everything was fine :> (except some sample rate problem that makes sound slow or fast, needed to be considered)

btw if you add some options for sample rate , channel and bit rate changes for output that would be grate ^^

thanks

**Comment by lostromb** [comment]
Pull the latest version of the package; I added automatic resampling that will solve the pitch problem.
You can change the bitrate or parameters mid-encode by just altering the values of the OpusEncoder object.
