### ISSUE TITLE
Incorrect version in output file

### ISSUE THREAD

**Issue by derek1982** [lostromb/concentus.oggfile#3]
Hi, I'm very impressed with the audio quality and speed of encoding in the Concentus project. There is a slight glitch in the output files metadata, which incorrectly suggests it was parsed with concentus.oggfile version 0.0.4 (please see below), although it was parsed with the most recent version (concentus.oggfile version 1.0.1). 
I don't think version numbers are required in the output file (just my personal opinion) because it implies a difference in audio quality, whereas concentus.oggfile is just parsing opus into an ogg container. I respect what you choose to do with that. 

A question I'd like to ask is if it's possible to omit the + 5 decibel header gain when encoding the file? I'm using ReplayGain for C# (NReplayGain) which works really well, but I'm concerned that 5 db will be added during playback. I've read that some opus software players ignore this +5db gain, while others utilise it. 

Thank you for porting opus to C#

![2017_04_17_1492426224](https://cloud.githubusercontent.com/assets/20665066/25087140/ba9864d2-2364-11e7-895a-332a36fd99df.png)

**Comment by lostromb** [comment]
Hmmmm....Well, most of these are just filler values that I kind of guessed / made up. The encoder field is super easy to change - I was just lazy and never bothered to bump that version number on release. You can go ahead and submit a one-line fix for that if you want.
ReplayGain is a little more interesting though, because this is what generates it:

```
short outputGain = 0;
_payloadIndex += WriteValueToByteBuffer(outputGain, _currentPayload, _payloadIndex); // Output gain in Q8
```

It's just fixed at 0x00 since I didn't want to really support it. I'm surprised, then, to see it being read back as 5 Db. Winamp's Opus plugin (BogProg) reads back the gain on my files as +0Db and so I assumed that was fine. But maybe it's not?

**Comment by derek1982** [comment]
Hi, thanks for your reply. Yeah, I've been an idiot :P
OpusTags opusTags = new OpusTags();
opusTags.Comment = "Concentus.OggFile";
![2017_04_17_1492444226](https://cloud.githubusercontent.com/assets/20665066/25094231/0c0bd744-238e-11e7-9a40-b874b8e128e6.png)

**Comment by lostromb** [comment]
I just changed the code to use the encoder library's version string instead of the container. But yet, if you're integrating this into a separate tool then you can go ahead and use your tool name there.

As for the 5Db gain, yeah, I have to assume that it's NReplayGain doing something fancy, since I always set it to 0 everywhere.
